### ISSUE TITLE
Fix the example in usage.rst

### ISSUE THREAD

**Issue by cuu508** [andrewthetechie/py-healthchecks.io#44]
Hello, 

First of all, kudos for making this package! I wanted to try it out, and I am a total newbie to async code, so looked at the usage examples and ran into issues:

```python
from healthchecks_io import AsyncClient, CheckCreate

async with AsyncClient(api_key="myapikey") as client:
    check = await client.create_check(CreateCheck(name="New Check", tags="tag1 tag2")
print(check)
```

* There's `CreateCheck` – I'm guessing it needs to be changed to `CheckCreate`?
* There's a missing closing ")"
* When I ran it, I got `SyntaxError: 'async with' outside async function`. Would be great to fix the example so that it would work as-is, with just putting a valid API key in

**Comment by andrewthetechie** [comment]
Thanks for the feedback. I cleaned up the examples in usage.rst so they should ready to go now.

Let me know if you have any other problems and I'll be happy to fix them up
