### ISSUE TITLE
Upgrade pydantic dependency to v2

### ISSUE THREAD

**Issue by Mariatta** [andrewthetechie/py-healthchecks.io#701]
**Is your feature request related to a problem? Please describe.**

Current version of healthchecks.io is incompatible with pydantic 2. There is an auto-update from dependabot in https://github.com/andrewthetechie/py-healthchecks.io/pull/700 however, due to major version upgrade, we need to do a bit more work to make it compatible with pydanticv2.

I'm using py-healthchecks.io along with another library that depends on pydantic v2, and due to the version conflict, I'm currently unable to use py-healthchecks.io.

**Describe the solution you'd like**
It would be great for py-healthchecks.io to support pydantic v2

**Describe alternatives you've considered**
We could keep it as is, but I imagine more and more libraries will be upgrading their pydantic dependency. Therefore, in order to keep py-healthchecks.io usable for other users, I recommend upgrading the version.

**Comment by andrewthetechie** [comment]
@Mariatta ty for opening a ticket. I would be happy to review and approve a PR that updates this project to use Pydantic 2

**Comment by Mariatta** [comment]
Thanks @andrewthetechie. I've created a PR at #702

**Comment by andrewthetechie** [comment]
@Mariatta thank you for your contribution. I don't use All-Contributors on this repo right now because its docs are still in RST format, but when I make that upgrade I'll make sure you're added.

Your change will be included in https://github.com/andrewthetechie/py-healthchecks.io/pull/671. I'm going to merge a few version bumps first and then try to get 0.4.3 out later today

**Comment by Mariatta** [comment]
Thank you!

**Comment by andrewthetechie** [comment]
I'd love some details on how you're using the library if you're free to share them. Its always exciting when someone new shows up using something I put together.

This library was a quick weekend project and I haven't thought about it much in a while

**Comment by andrewthetechie** [comment]
@Mariatta 0.4.3 is available now https://pypi.org/project/healthchecks-io/0.4.3/

**Comment by Mariatta** [comment]
Thank you @andrewthetechie!
